import re

city_mapping = {
'Mary' : 'میری',
'Alfred Nobel' : 'الفریڈ نوبل',
'Tom' : 'ٹام',
'norway' : 'ناروے',
'Edo' : 'ایڈو',
'Tokyo' : 'ٹوکیو',
'Elvis Presley' : 'الوس پریسلی',
'Luke' : 'لوک',
'Boston' : 'بوسٹن',
'Bolivia' : 'بولیویا',
'Pretoria' : 'پریٹوریا',
#'Côte d'Ivoire' : 'کوٹ ڈی آوائر',
'Libya' : 'لیبیا',
'Yokohama' : 'یوکوہاما',
'Kobe' : 'کوبے',
'Zhao' : 'زھاؤ',
'John Lennon' : 'جان لینن',
'Paul McCartney' : 'پال مک کارٹنی',
'George Harrison' : 'جارج ہیریسن',
'Ringo Star' : 'رنگو سٹار',
'Mifune' : 'میفیونی',
'Ken' : 'کین',
'Heather' : 'ہیتھر',
'Chad' : 'چاڈ',
'Yumi' : 'یومی',
'estonia' : 'اسٹونیا',
'John' : 'جان',
'Rodica' : 'روڈیکا',
'Russia' : 'روسیہ',
'Ann' : 'این',
'Sweden' : 'سویڈن',
'China' : 'چین',
'russia' : 'روسیہ',
'Japan' : 'جاپان',
'Canada' : 'کینیڈا',
'Roosevelt' : 'روزوولٹ',
'Kiesbauer' : 'کیس باؤر',
'Tel Aviv' : 'ٹیل ایویو',
'switzerland' : 'سوئٹزرلینڈ',
'Frank' : 'فرینک',
'Elena' : 'ایلینا',
'Liu Xiaobo' : 'لیو ژاؤبو',
'china' : 'چین',
'Liu Bei' : 'لیو بی',
'Zhuge Liang' : 'ژوگ لیانگ',
'Italy' : 'اٹلی',
'Warren Harding' : 'وارن ہارڈنگ',
'Aaron Copland' : 'ایرون کوپلینڈ',
'Scrooge' : 'اسکروج',
'Jack' : 'جیک',
'Brazil' : 'برازیل',
'Mitt Romney' : 'مٹ رومنی',
'Massachusetts' : 'میساچوسٹس',
'Naoki' : 'ناؤکی',
'Leo Tolstoy' : 'لیو ٹولسٹوئ',
'Wilkins' : 'ولکنز',
'Joan' : 'جوآن',
'France' : 'فرانس',
'Frederick' : 'فریڈرک',
'Keeton' : 'کیٹن',
'Brian' : 'برائن',
'Ogawa' : 'اوگاوا',
'England' : 'انگلینڈ',
'David Beckham' : 'ڈیوڈ بیکہم',
'America' : 'امریکا',
'Ai' : 'عائی',
'Lech' : 'لیچ',
'Merry' : 'میری',
'america' : 'امریکا',
'Bob Marley' : 'باب مارلی',
'Alice' : 'ایلس',
'Charles Dickens' : 'چارلس ڈکنز',
'Coleridge' : 'کولرج',
'Patterson' : 'پیٹرسن',
'Hitler' : 'ہٹلر',
'Buenos Aires' : 'بوئنس آئرس',
'Argentina' : 'ارجنٹائن',
'Kate' : 'کیٹ',
'Kerensky' : 'کیرینسکی',
'Germany' : 'جرمنی',
'Rome' : 'روم',
'Mayuko' : 'میوکو',
'Miriam' : 'مریم',
'Thomas' : 'تھامس',
'germany' : 'جرمنی',
'Kanazawa' : 'کنازوا',
'Marie' : 'ماری',
'Nara' : 'نارا',
'Ibrahim Sofu' : 'ابراہیم صوفو',
'Metin Kaplan' : 'میتن کپلان',
'Klaus Pohl' : 'کلاس پوہل',
'Darwin' : 'ڈارون',
'Nagoya' : 'ناگویا',
'Kyoto' : 'کیوٹو',
'france' : 'فرانس',
'Bikini Atoll' : 'بکینی اٹول',
'Nelson Mandela' : 'نیلسن مانڈیلا',
'New Delhi' : 'نیو ڈےلی',
'Chuck' : 'چک',
'Berlin' : 'برلن',
'Norman Finkelstein' : 'نورمن فنکلسٹائن',
'Bob' : 'باب',
'Tehran' : 'تہران',
'Smith' : 'اسمتھ',
'San Francisco' : 'سان فرانسسکو',
'Sue' : 'سو',
'John Quincy Adams' : 'جان کوئنسی ایڈمز',
'Liisa' : 'لیزا',
'Jane' : 'جین',
'New Yersey' : 'نیو جرسی',
'Liverpool' : 'لیورپول',
'Maldives' : 'مالدیوز',
'El-Nashar' : 'ال نشار',
'Egypt' : 'مصر',
'Jim' : 'جم',
'Scotland' : 'اسکاٹ لینڈ',
'Wendy' : 'وینڈی',
'japan' : 'جاپان',
'Tony' : 'ٹونی',
'Laura' : 'لارا',
'Susan' : 'سوزن',
'Narita' : 'نریٹا',
'Sachiyo' : 'سچیو',
'Greece' : 'یونان',
'Louis Riel' : 'لوئس ریئل',
'Scott' : 'اسکاٹ',
'San Jose' : 'سین جوزے',
'Iran' : 'ایران',
'Steve' : 'اسٹیو',
'Carl Smith' : 'کارل اسمتھ',
'Dan' : 'ڈین',
'canada' : 'کینیڈا',
'Australia' : 'آسٹریلیا',
'Maria' : 'ماریا',
'Athens' : 'اتھنز',
'Chicago' : 'چکاگو',
'Nancy Ianiero' : 'نینسی ائیریئرو',
'Mexico' : 'میکسیکو',
'Lancelot' : 'لینسلوٹ',
'Arthur' : 'آرتھر',
'Guinevere' : 'گوئنیور',
'Hiroshima' : 'ہیروشیما',
'Detroit' : 'ڈیٹرائٹ',
'george walker bush' : 'جارج واکر بش',
'Connecticut' : 'کنیکٹیکٹ',
'Kamal' : 'کمال',
'Anwar Sadat' : 'انور صادات',
'Zinedine Zidane' : 'زینیڈین زیدان',
'Thierry Henry' : 'تھیری ہنری',
'Ronaldo' : 'رونالڈو',
'Mabel Normand' : 'میبل نارمینڈ',
'Hokkaido' : 'ہوکائیڈو',
'Gerhard Sundt' : 'گرہارڈ سنڈٹ',
'Austria' : 'آسٹریا',
'Richard Roberts' : 'رچرڈ روبرٹس',
'brazil' : 'برازیل',
'Gene Bartow' : 'جین بارٹو',
'Vietnam' : 'ویتنام',
'Brown' : 'براؤن',
'Vienna' : 'ویئنا',
'Paul' : 'پال',
'Marc' : 'مارک',
'Sapporo' : 'سپورو',
'Munich' : 'میونخ',
'Michelangelo Antonioni' : 'مائیکل اینجیلو اینٹونیونی',
'White' : 'وائٹ',
'New York' : 'نیو یارک',
'London' : 'لندن',
'Betty' : 'بیٹی',
'Sachiko' : 'سچیکو',
'Jorge' : 'ہورحے',
'Michael Crichton' : 'مائکل کرائٹن',
'Laurie' : 'لاری',
'Melbourne' : 'ملبورن',
'Little Johnny' : 'لٹل جانی',
'Antonio' : 'انٹونیو',
'Ford' : 'فورڈ',
'Illinois' : 'الینوئس',
'Missouri' : 'مسوری',
'Nick Leeson' : 'نک لیسن',
'Millie' : 'ملی',
'Ricardo' : 'رکارڈو',
'Madonna' : 'مڈونا',
'Saad Hariri' : 'سعد حریری',
'Lebanon' : 'لبنان',
'Marilyn Manson' : 'میرلن منسن',
'Becker' : 'بیکر',
'austria' : 'آسٹریا',
'Gilbert Schaller' : 'گلبرٹ شالر',
'Anthony Blunt' : 'انتھونی بلنٹ',
'Joe' : 'جو',
'Hitomi' : 'ہٹومی',
'George Washington' : 'جارج واشنگٹن',
'Emily' : 'ایملی',
'Pakistan' : 'پاکستان',
'Dallas' : 'ڈیلاس',
'Kim' : 'کم',
'Joseph Wilson' : 'جوزیف ولسن',
'Andorra' : 'اینڈورا',
'United States' : 'یونائیٹڈ اسٹیٹس',
'Ben' : 'بین',
'Éamonn' : 'ایمون',
'Lucy' : 'لوسی',
'Lidya' : 'لڈیا',
'Green' : 'گرین',
'Paris' : 'پیرس',
'britain' : 'برٹن',
'India' : 'بھارت',
'Ted' : 'ٹیڈ',
'Elizabeth' : 'الزبیتھ',
'Bill' : 'بل',
'Roy' : 'رائی',
'Pearl Primus' : 'پرل پریمس',
'California' : 'کیلیفورنیا',
'Taninna' : 'تنینا',
'Dick' : 'ڈک',
'Babe Ruth' : 'بیب روتھ',
'Yoko' : 'یوکو',
'Linda' : 'لنڈا',
'Edith Piaf' : 'ایڈت پیاف',
'Budapest' : 'بوڈاپسٹ',
'Bavaria' : 'بووریا',
'Bob Dylan' : 'باب ڈلین',
'Fukui' : 'فکوئی',
'Spain' : 'ہسپانیہ',
'Edison' : 'ایڈیسن',
'Tycho Brahe' : 'ٹائکو براہی',
'Fredrik' : 'فریڈرک',
'Carl Lewis' : 'کارل لوئس',
'Beijing' : 'بیجنگ',
'Picasso' : 'پیکاسو',
'Israel' : 'اسرائیل',
'René Capistran Garza' : 'رینے کاپسٹران گارزا',
'Alexandria' : 'الیگزینڈریا',
'philippines' : 'فلپائنز',
'Naoko' : 'ناؤکو',
'Samuel' : 'صموئیل',
'Cuba' : 'کیوبا',
'Tbilisi' : 'ٹبلیسی',
'John Dillinger' : 'جان ڈلنجر',
'ireland' : 'آئرلینڈ',
'Ned' : 'نیڈ',
'Utah' : 'یوٹاہ',
'Ruth' : 'روتھ',
'Rabin' : 'رابین',
'Deng Xiaoping' : 'ڈینگ شاؤ پنگ',
'Dale Evans' : 'ڈیل ایونز',
'Avilov' : 'اویلوف',
'Muhammed' : 'محمد',
'Mecca' : 'مکہ',
'Iceland' : 'آئس لینڈ',
'Gian Antonio Maggi' : 'جین انٹونیو میگی',
'Giulio Vivanti' : 'جولیو ویوانتی',
'Daniel' : 'ڈینیل',
'Los Angeles' : 'لاس اینجلس',
'Seoul' : 'سیؤل',
'Kenza' : 'کینزا',
'UK' : 'یوکے',
'Hughes' : 'ہیوز',
'Gracia' : 'گریشیا',
'Urumqi' : 'ارومچی',
'Napoleon' : 'نپولئون',
'Elba' : 'ایلبا',
'Barcelona' : 'بارسلونا',
'Tom Jackson' : 'ٹام جیکسن',
'hawaii' : 'ہوائی',
'croatia' : 'کروئیشیا',
'Iva Majoli' : 'ایوا مجولی',
'Constantinople' : 'قسطنطنوپل',
'Louisiana' : 'لوزیانا',
'Britney Spears' : 'برٹنی اسپیئرز',
'Roger Miller' : 'راجر ملر',
'Fort Worth' : 'فورٹ ورتھ',
'Texas' : 'ٹیکسس',
'Romania' : 'رومانیا',
'Karen' : 'کی رن',
'Justin Bieber' : 'جسٹن بیبر',
'Saskatchewan' : 'سسکیچوان',
'Alexander' : 'الیکزینڈر',
'Babylon' : 'بابل',
'clive staple lewis' : 'کلائو اسٹیپل لوئس',
'Keats' : 'کیٹس',
'Henry Ford' : 'ہینری فورڈ',
'Frederick West' : 'فریڈرک ویسٹ',
'Croatia' : 'کروئیشیا',
'Meg' : 'میگ',
'George Wallace' : 'جارج والس',
'Charles I' : 'چارلس اول',
'Qin Shi Huang' : 'قن شی ہوانگ',
'Einstein' : 'انسٹائن',
'thailand' : 'تھائی لینڈ',
'Vlad the Impaler' : 'ولیڈ دی امپیلر',
'Matsuyama' : 'متسیاما',
'Julio' : 'جولیو',
'Agnès' : 'اگنیس',
'australia' : 'آسٹریلیا',
'Andy Whitfield' : 'اینڈی وٹفیلڈ',
'Yunus' : 'یونس',
'Stephen Hawking' : 'اسٹیون ہاوکنگ',
'Alexander Hamilton' : 'الیگزینڈر ہیملٹن',
'Sylvia' : 'سلویا',
'Alsace' : 'الزیس',
#'Lupita Nyong'o' : 'لوپیتا نیونگو',
'Peter Jackson' : 'پیٹر جیکسن',
'Mauritania' : 'موریٹینیا',
'Florence' : 'فلورنس',
'Cairo' : 'کائرو',
'Okinawa' : 'اوکیناوا',
'De Jong' : 'دی جونگ',
'Melanie' : 'میلینی',
'Singapore' : 'سنگاپور',
'Ellen' : 'ایلن',
'Sappho' : 'سفو',
'lesbos' : 'لیسبوس',
'Ooita' : 'اوئٹا',
'Osaka' : 'اوساکا',
'Charlotte Brontë' : 'چارلٹ برونٹ',
'united kingdom' : 'یونائیٹڈ کنگڈم',
'belgium' : 'بیلجیم',
'Leona Helmsley' : 'لیونا ہیلمسلی',
'poland' : 'پولینڈ',
'Muiriel' : 'میریل',
'Niels Bohr' : 'نیلز بوئر',
'Madrid' : 'میڈرڈ',
'Hashimoto' : 'ہاشیموٹو',
'Kinshasa' : 'کنشاسا',
'Democratic Republic of the Congo' : 'جمہوریہ کانگو کنگو',
'Mike' : 'مائک',
'Goethe' : 'گوتھ',
'Mori Ogai' : 'موری اوگائی',
'Putin' : 'پوٹن',
'Kieslowski' : 'کیسلووسکی',
'sweden' : 'سویڈن',
'Burt Lancaster' : 'برٹ لانکسٹر',
'Bill Clinton' : 'بل کلنٹن',
'Teresa' : 'ٹریسا',
'Yugoslavia' : 'یوگوسلاویا',
'Karim' : 'کریم',
'Rudolf' : 'روڈولف',
'Ireland' : 'آئرلینڈ',
'Sandra Goudie' : 'سندرا گودی',
'Max Purnell' : 'میکس پرنیل',
'Emil Fischer' : 'امیل فشر',
'Harry Potter' : 'ہیری پوٹر',
'Coventry' : 'کوونٹری',
'Luis' : 'لوئس',
'Cristina' : 'کرسٹینا',
'Beethoven' : 'بیتھوون',
'Allan Chapman' : 'الن چیپمین',
'Bush' : 'بش',
'Barbara' : 'باربرا',
'Mark' : 'مارک',
'Obama' : 'اوباما',
'Finland' : 'فن لینڈ',
'Meryem' : 'مریم',
'Adolf Hitler' : 'ایڈولف ہٹلر',
'usa' : 'ریاستہائے متحدہ',
'vietnam' : 'ویتنام',
'Simone Signoret' : 'سمون سگنوری',
'Nelson Beavers' : 'نیلسن بیورز',
'Maurice Papon' : 'ماریس پاپون',
'Muhammad Ali' : 'محمد علی',
'Robert' : 'رابرٹ',
'Ohio' : 'اوہائیو',
'John Dalton' : 'جان ڈالٹن',
'Brian Goodell' : 'برائن گوڈیل',
'Yamaha' : 'یاماہا',
'Nagasaki' : 'ناگاساکی',
'Jerry Reinsdorf' : 'جیری رائنسڈورف',
'Venice' : 'وینس',
'St. John' : 'سینٹ جان',
'Mohamed Dib' : 'محمد دب',
'algeria' : 'الجیریا',
'Bali' : 'بالی',
'Kim Il Sung' : 'کم السنگ',
'Mike Tyson' : 'مائک ٹائسن',
'Buffalo' : 'بفیلو',
'Pedro' : 'پیڈرو',
'Nebraska' : 'نیبراسکا',
'Lori' : 'لوری',
'Odette' : 'اوڈیٹ',
'Nantes' : 'نانٹیس',
'Shikoku' : 'شیکوکو',
'Britain' : 'برٹین',
'Stefan Edberg' : 'اسٹیفن ایڈبرگ',
'Bell' : 'بیل',
'Gianni Versace' : 'جیانی ورسیچی',
'Andre Agassi' : 'انڈری اگاسی',
'Jill' : 'جل',
'Switzerland' : 'سوئٹزرلینڈ',
'Pribilof Islands' : 'پریبلوف آئلینڈز',
'Yamada' : 'یامادا',
'Hans' : 'ہانس',
'Punch' : 'پنچ',
'Julia' : 'جولیا',
'Piet Mondrian' : 'پیٹ منڈریان',
'Nixon' : 'نکسن',
'Tom Hunter' : 'ٹام ہنٹر',
'Iraq' : 'عراق',
'Bill Gates' : 'بل گیٹس',
'Pinocchio' : 'پینوکیو',
'Netherlands' : 'نیدرلینڈز',
'Hawk' : 'باز',
'Baker' : 'بیکر',
'Niigata' : 'نیگٹا',
'Genevieve de Gaulle-Anthonics' : 'جینوویو دی گال-انتھونکس',
'Charles de Gaulle' : 'چارلز ڈی گال',
'French' : 'فرانس',
'USA' : 'ریاستہائے متحدہ',
'Chabrol' : 'چبرول',
'Leonardo da Vinci' : 'لئونارڈو ڈا ونسی',
'south africa' : 'جنوبی افریقا',
'Tom Cruise' : 'ٹام کروز',
'Ukraine' : 'یوکرائن',
'korea' : 'کوریا',
'Marco' : 'مارکو',
'Paulo' : 'پاؤلو',
'Malta' : 'مالٹا',
'John Paul II' : 'جان پول دوسرا',
'Poland' : 'پولینڈ',
'Kennedy' : 'کینیڈی',
'Zaire' : 'زائر',
'Hooper' : 'ہوپر',
'Portland' : 'پورٹلینڈ',
'Jesus' : 'عیسیٰ',
'Eva Peron' : 'اووا پیرون',
'california' : 'کیلیفورنیا',
'Walt' : 'والٹ',
'Akira' : 'اکیرا',
'Schubert' : 'شوبیرٹ',
'Leloir' : 'لیلوآر',
'Guatemala' : 'گواٹیمالا',
'Thomas Edison' : 'تھامس ایڈیسن',
'Swift' : 'اسوفٹ',
'South Africa' : 'جنوبی افریقا',
'Sumatra' : 'سوماٹرا',
'Jones' : 'جونز',
'Michael Jackson' : 'مائیکل جیکسن',
'Kazakhstan' : 'کزاخستان',
'Sendai' : 'سینڈائی',
'Yamamoto' : 'یاماموٹو',
'italy' : 'اٹلی',
'spain' : 'ہسپانیہ',
'Alexander the Great' : 'الیگزینڈر دی گریٹ',
'Harry' : 'ہیری',
'Tusnelda' : 'ٹسنیلڈا',
'Arminio' : 'ارمینیو',
'Freud' : 'فرویڈ',
'Hebron' : 'ہیبرون',
'James' : 'جیمس',
'Carrie Tomlinson' : 'کیری ٹوملنسن',
'John Bower' : 'جان باؤر',
'Sri Lanka' : 'سری لنکا',
'Robert Frost' : 'روبرٹ فروسٹ',
'Evliya Celebi' : 'اولیہ چلیبی',
'turkey' : 'ترکی',
'George' : 'جارج',
'Marco Polo' : 'مارکو پولو',
'Leeds' : 'لیڈز',
'us' : 'ریاستہائے متحدہ',
'Samir' : 'سمیر',
'Helen' : 'ہیلن',
'Lalita' : 'للیتا',
'Rosa' : 'روزا',
'Emile Zola' : 'ایمیل زولا',
'Bombay' : 'بمبئی',
'Norway' : 'ناروے',
'Belgium' : 'بیلجیم',
'Rio de Janeiro' : 'ریو دی جینیرو',
'Andres Escobar' : 'اینڈریس ایسکوبار',
'colombia' : 'کولمبیا',
'syria' : 'سوریہ',
'bavaria' : 'باوریا',
'egypt' : 'مصر',
'Clinton' : 'کلنٹن',
'Al Gore' : 'آل گور',
'Washington DC' : 'واشنگٹن ڈی سی',
'Sarah' : 'سارا',
'Zola' : 'زولا',
'damascus' : 'دمشق',
'Syria' : 'سوریہ',
'Lida' : 'لیدا',
'Suzanne' : 'سوزین',
'Wang' : 'ونگ',
'Raman Raghav' : 'رامن راغوان',
'finland' : 'فن لینڈ',
'Marilyn Monroe' : 'میرلن منرو',
'Natasha' : 'نتاشا',
'Judy' : 'جوڈی',
'Frank Sinatra' : 'فرینک سناٹرا',
'Malaysia' : 'ملائیشیا',
'Maximilian' : 'میکسیملین',
'Sophie' : 'صوفی',
'Brandon Lee' : 'برینڈن لی',
'Tyler Jackson' : 'ٹائلر جیکسن',
'Charlemagne' : 'چارلمین',
'Ayrton Senna' : 'ایرٹن سینا',
'Tunisia' : 'تیونیشیا',
'Gisèle' : 'جیسل',
'Munch' : 'منچ',
'Berlioz' : 'برلیوز',
'North Carolina' : 'شمالی کیرولائنا',
'New Orleans' : 'نیو اورلینز',
'Walt Disney' : 'والٹ ڈزنی',
'Rhode Island' : 'روڈ آئلینڈ',
'kenya' : 'کینیا',
'Portugal' : 'پرتگال',
'Kyushu' : 'کیوشو',
'Castro' : 'کاسٹرو',
'Paolo' : 'پاؤلو',
'Schneider' : 'شنائیڈر',
'Azerbaijan' : 'آذربائیجان',
'Lenz' : 'لینز',
'Ichiro' : 'ایچیرو',
'Klagenfurt' : 'کلاگنفورٹ',
'Holy' : 'ہولی',
'Lisa Lillien' : 'لیسا للین',
'Dan Schneider' : 'ڈین شنائیڈر',
'Ikeda' : 'اکیڈا',
'Tom Kalinske' : 'ٹام کالنسکی',
'Baena Soares' : 'بائینا سوئرس',
'Salt Lake City' : 'سالٹ لیک سٹی',
'Amelia Earhart' : 'امیلیا ائیرہارٹ',
'Curtis' : 'کرٹس',
'Edward' : 'ایڈورڈ',
'Taro' : 'تارو',
'Kawasaki' : 'کاواساکی',
'Vance' : 'وینس',
'Sato' : 'ساتو',
'Cameron' : 'کیمرون',
'Saburo' : 'سبورو',
'Michigan' : 'مشیگن',
'Napoleon Bonaparte' : 'نیپولئون بوناپارٹ',
'Corsica' : 'کورسیکا',
'Noriko' : 'نوریکو',
'Brad Pitt' : 'بریڈ پٹ',
'Valentina Tereshkova' : 'ویلنٹائنا ٹیریشکووا',
'Marrakesh' : 'مراکیش',
'Hanako' : 'ہاناکو',
'Yana' : 'یانا',
'england' : 'انگلینڈ',
'Susan Greene' : 'سوزن گرین',
'Pskov' : 'پسکوو',
'Yitzhak Rabin' : 'یٹسحاک رابن',
'Oslo' : 'آسلو',
'Weinrich' : 'وائنریچ',
'hungary' : 'ہنگری',
'Chelsea' : 'چیلسی',
'Anne' : 'این',
'Moncalvo' : 'منکالو',
'Bruce' : 'بروس',
'Sam' : 'سام',
'Gifu' : 'گیفو',
'Maciek' : 'میسیک',
'Eve' : 'ایو',
'Lincoln' : 'لنکن',
'Edu' : 'ایڈو',
'Tony Blair' : 'ٹونی بلیئر',
'Mel Karmazin' : 'میل کرمازین',
'Aachen' : 'آخن',
'Bach' : 'باخ',
'Holland' : 'ہولینڈ',
'Trang' : 'ٹرینگ',
'Brian Eno' : 'برائن اینو',
'washington, d.c.' : 'واشنگٹن ڈی سی',
'Tracy' : 'ٹریسی',
'Wood' : 'وڈ',
'Pua' : 'پوا',
'Peru' : 'پیرو',
'Lin Piao' : 'پیرو',
'Rutherford Hayes' : 'رذرفرڈ ہیز',
'Shinji Ono' : 'شنجی اونو',
'mexico' : 'میکسیکو',
'Aurelie' : 'اوریلی',
'Peter' : 'پیٹر',
'Turkey' : 'ترکی',
'Nick' : 'نک',
'Ana' : 'انا',
'Morocco' : 'مروکو',
'Hans Christian Anderson' : 'ہنس کرسٹین اینڈرسن',
'netherlands' : 'نیدرلینڈز',
'Rosario Ibarra' : 'روزاریو ایبرا',
'Carl' : 'کارل',
'john fitzgerald kennedy' : 'جان فٹزجیرلڈ کینیڈی',
'Mae West' : 'می ویسٹ',
'ethiopia' : 'ایتھوپیا',
'Sidney Sheldon' : 'سنی شیلڈن',
'Patricia' : 'پیٹریشیا',
'Jerusalem' : 'یروشلم',
'Jan De Bont' : 'جان ڈی بونٹ',
'Gabriel Garcia Marquez' : 'گیبریل گارسیا مارکیز',
'Johann Wolfgang von Goethe' : 'جوہان وولفگینگ فون گوتھ',
'Carla' : 'کارلا',
'Achille' : 'اکیل',
'West Germany' : 'مغرب',
'Kumi' : 'کیمی',
'Marlowe' : 'مارلو',
'York' : 'یارک',
'Stephen Harper' : 'اسٹیفن ہارپر',
'Chris' : 'کرس',
'Beth' : 'بیتھ',
'Tanzania' : 'تنزانیہ',
'Nancy' : 'نینسی',
'Keisuke' : 'کیسکے',
'Jackson' : 'جیکسن',
'William Wallace' : 'ولیم والیس',
'Newton' : 'نیوٹن',
'Grant' : 'گرانٹ',
'Vicksburg' : 'وکسبرگ',
'Hansson' : 'ہانسن',
'Lady of the Lake' : 'لیڈی آف د لیک',
'Merlin' : 'مرلن',
'Magdalena' : 'میگڈالینا',
'Costas Simitis' : 'کوستاس سمیتیس',
'Simitis' : 'سمیتیس',
'Edgar Degas' : 'ایڈگر ڈیگاس',
'André Henri Constant van Hasselt' : 'اینڈرے انری کونسٹینٹ ون ہاسلٹ',
'Maastricht' : 'ماسٹرکٹ',
'Emi' : 'ایمی',
'Kashgar' : 'کاشغر',
'Jenninger' : 'جیننگر',
'Buzz Aldrin' : 'بز الڈرن',
'Hobday' : 'ہابڈے',
'Jeannie' : 'جینی',
'Jiro' : 'جیرو',
'Taiwan' : 'تائیوان',
'Hanover' : 'ہینوور',
'Jyestadeva' : 'جئیشتادیوا',
'St. Helena' : 'سینٹ ہیلینا',
'Taro Akagawa' : 'تارو اکاگاوا',
'Luna' : 'لونا',
'Doi' : 'ڈوئی',
'Eugenio Montale' : 'یوجینیو منٹیل',
'Normandy' : 'نارمینڈی',
'Alaska' : 'الاسکا',
'Irving Mitchell Felt' : 'ارونگ مٹشل فیلٹ',
'Brett Favre' : 'بریٹ فاور',
'india' : 'بھارت',
'Chen' : 'چین',
'Sao Paulo' : 'ساؤ پالو',
'Miguel Indurain' : 'مگوئل انڈورائن',
'Zambia' : 'زیمبیا',
'Edgar Allen Poe' : 'ایڈگر ایلن پو',
'Gottfried Reinhardt' : 'گوتفرید رینہارٹ',
'Dawson' : 'ڈاوسن',
'Quentin Tarantino' : 'کوئنٹن ٹیرانٹینو',
'Ecuador' : 'ایکواڈور',
'Emet' : 'ایمیٹ',
'Margaret' : 'مارگریٹ',
'Alex Marcelo' : 'الیکس مارسیلو',
'Jacques' : 'جیکس',
'Vladislav Listyev' : 'ولادیسلاو لیسٹیو',
'Moscow' : 'ماسکو',
'Charlie Chaplin' : 'چارلی چپلن',
'Markku' : 'مارکو',
'Filiberto' : 'فلیبرٹو',
'Istanbul' : 'استنبول',
'Abrams' : 'ابرامز',
'Browne' : 'براؤن',
'Anna' : 'انا',
'Delhi' : 'دہلی',
'Heligoland' : 'ہیلیگولینڈ',
'Ramu' : 'رامو',
'Edvard Munch' : 'ایڈوارڈ منک',
'São Paulo' : 'ساؤ پالو',
'Fabio' : 'فابیو',
'Shanghai' : 'شنگھائی',
'Lisbon' : 'لسبن',
'Baghdad' : 'بغداد',
'Javier' : 'جاویر',
'Marge' : 'مارج',
'Afghanistan' : 'افغانستان',
'Laura Ingalls' : 'لارا انگلز',
'Seattle' : 'سیٹل',
'Romano Prodi' : 'رومانو پروڈی',
'Paola' : 'پاؤلا',
'Elvis' : 'الوس',
'Sita' : 'سیتا',
'Las Vegas' : 'لاس ویگاس',
'Sherlock Holmes' : 'شرلوک ہولمز',
'Somalia' : 'سومالیہ',
'Indonesia' : 'انڈونیشیا',
'Lopez' : 'لوپیز',
'North Korea' : 'شمالی کوریا',
'Cat Stevens' : 'کیٹ اسٹیونز',
'Roger Vercel' : 'راجر ورسل',
'Oleg' : 'اولیگ',
'al-Maliki' : 'المالکی',
'Hadley' : 'ہیڈلی',
'Felipe González Márquez' : 'فلیپی گونزالیس مارکیز',
'Howard Caine' : 'ہووارڈ کین',
'Korea' : 'کوریا',
'Begum' : 'بیگم',
'Leipzig' : 'لائپزگ',
'Snow White' : 'برفانا',
'Jerry Garcia' : 'جیری گارسیا',
'Sylvia Costas' : 'سلویا کوسٹاس',
'Andy Sipowicz' : 'اینڈی سپوویز',
'Steven Jenkins' : 'اسٹیون جینکنز',
'mongolia' : 'منگولیا',
'Algeria' : 'الجیریا',
'Alfredo Cristiani' : 'الفریڈو کریسٹیانی',
'hamburg' : 'ہیمبرگ',
'Yoshio' : 'یوشیو',
'Tina Turner' : 'ٹینا ٹرنر',
'Thailand' : 'تھائی لینڈ',
'Rachel Carson' : 'ریچل کارسن',
'Elaine' : 'ایلین',
'Keiko' : 'کیکو',
'Virginia Woolf' : 'ورجینیا وولف',
'Pierrot' : 'پیرو',
'Tanaka' : 'تناکا',
'Catherine the Great' : 'کیٹڱرین دی گریٹ',
'Sally' : 'سیلی',
'Chopin' : 'چوپان',
'Marie Antoinette' : 'ماری انٹوائنٹ',
'Basra' : 'بصرہ'
}

# Define a regular expression pattern to match city urdu_names (both single and multi-word)
pattern = r'\b(?:' + '|'.join(re.escape(city) for city in city_mapping.keys()) + r')\b'

with open('augmentation/augmentation_without_urdu_alignment/adjectives/adjective_aug_sbn_only_eng.txt', 'r') as main, open(
        'augmentation/augmentation_without_urdu_alignment/adjectives/adjective_aug_sbn_only_urdu.txt', 'w') as done:
    text = main.read()


    def replace_city(match):
        city = match.group()
        return city_mapping.get(city, city)


    # Use a function to replace the matched city name
    modified_text = re.sub(pattern, replace_city, text, flags=re.IGNORECASE)
    done.write(modified_text)